nsapiVersion: networking.k8s.io/v2
kind: Ingress
metadata:
  name: jenkins-ingress
  namespace: devops-tools
  annotations:
    ingressClassName: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: automa
      http:
        paths:
          - path: /jenkins/
            pathType: Prefix
            backend:
              service:
                name: jenkins-service
                port:
                  number: 8080
          - path: /jenkins/jnlp
            pathType: Prefix
            backend:
              service:
                name: jenkins-service
                port:
                  number: 50000
