apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins-ingress
  namespace: devops-tools
annotations:
  kubernetes.io/ingress.class: nginx
  nginx.ingress.kubernetes.io/ssl-redirect: “true”
spec:
  tls:
      – hosts: jenkins.automa
  rules:
    – host: jenkins.automa
        http:
          paths:
            – path: /
              pathType: Prefix
              backend:
                service:
                  name: jenkins-service
                    port:
                    number: 8080
            – path: /jnlp
              pathType: Prefix
              backend:
                service:
                  name: jenkins-service
                  port:
                    number: 50000
